import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ToastWrapper from "@/components/ToastProvider";
import ReactQueryProvider from "@/components/ReactQueryProvider";

import "./global.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Calculadora de prestaciones de ley",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <ToastWrapper>{children}</ToastWrapper>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
